In [2]:
num= int(input("num :"))

if num%2 == 0 :
    print("짝수")
else :
    print("홀수")

num : 1


홀수


In [3]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    if x == "apple":
        print("사과")
    elif x == "banana":
        print("바나나")
    elif x == "cherry":
        print("체리")

사과
바나나
체리


In [34]:
for i in range(1,11):
    if i % 2 ==0:
        continue
        
    print(i)
    
    if i == 5:
        break

1
3
5


In [36]:
numbers = [1,2,3,4,5]
sum_of_numbers = 0

for num in numbers:
    sum_of_numbers += num
    
print("리스트의 합:", sum_of_numbers)

리스트의 합: 15


In [43]:
numbers1 = [1,2,3,4,5]
numbers2 = [6,7,8,9,10]

list = []
for i in range(5):
    list.append(numbers1[i] + numbers2[i])

print(list)

[7, 9, 11, 13, 15]


In [46]:
def greet(name):
    print("Hi " + name)
    print("Nice to see you again!")
    print("Enjoy our video")
    
greet("Peter")

Hi Peter
Nice to see you again!
Enjoy our video


In [64]:
def avg(l):
    s = 0
    for i in l:
        s += i
    return s/(len(l))
print(numbers)
avg(numbers)

[1, 2, 3, 4, 5]


3.0

In [2]:
import person

p1 = person.Person("Hong",20,"Here")

p1.greeting()

안녕하세요, 저는 Hong입니다


In [7]:
s1 = person.Student("Kim", 21, "there")

p1.greeting()
s1.greeting()
p1.info()
s1.info()

안녕하세요, 저는 Hong입니다
안녕하세요, 저는 Kim입니다
이름 : Hong, 나이 : 20
이름 : Kim, 나이 : 21, 주소 : there


In [12]:
import numpy as np

z= np.zeros(10)

print(z)

t = np.arange(10)
print(t)
type(t)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [14]:
list1 = [1,2]
list2 = [3,4]
list1+list2

[1, 2, 3, 4]

In [16]:
numpy1 = np.array([1,2])
numpy2 = np.array([3,4])
numpy1+numpy2

array([4, 6])

In [18]:
numpy1 +=1
numpy1

array([3, 4])

In [23]:
numpy2x = np.array([[1,2],[3,4]])
numpy2x

array([[1, 2],
       [3, 4]])

In [24]:
numpy2x.shape

(2, 2)

In [43]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a.shape

(3, 3)

In [40]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [117]:
a.shape

(3, 2, 2)

In [210]:
a.ndim

1

In [211]:
a.size

3

In [46]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [48]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
a = np.arange(1,10)
type(a)

numpy.ndarray

In [55]:
a[1:3]

array([2, 3])

In [58]:
my_numpy = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
my_numpy

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [212]:
my_numpy.shape

(3, 4)

In [214]:
my_numpy.size

12

In [215]:
my_numpy.ndim

2

In [84]:
new_numpy = my_numpy[0:2,0:2]
new_numpy

array([[1, 2],
       [5, 6]])

In [79]:
a = np.arange(12).reshape(3,2,2)
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [82]:
aa = np.arange(1,13).reshape(3,4)
aa

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
na = aa[[0,1,2],[0,1,0]]
na

array([1, 6, 9])

In [93]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
b.sum(axis=1)

array([ 6, 22, 38])

In [99]:
b.sum()

66

In [100]:
b.min(axis=1)

array([0, 4, 8])

In [102]:
b.min()

0

In [114]:
array1 = np.arange(27).reshape(3,3,3)
array2 = np.arange(3)
array3 = array1 + array2
array1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [115]:
array2

array([0, 1, 2])

In [119]:
array3

array([[[ 0,  2,  4],
        [ 3,  5,  7],
        [ 6,  8, 10]],

       [[ 9, 11, 13],
        [12, 14, 16],
        [15, 17, 19]],

       [[18, 20, 22],
        [21, 23, 25],
        [24, 26, 28]]])

In [121]:
a = np.arange(3)
a

array([0, 1, 2])

In [123]:
a*a

array([0, 1, 4])

In [125]:
b = np.arange(3).reshape(3,1)
b

array([[0],
       [1],
       [2]])

In [127]:
a*b

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [129]:
b*a

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [134]:
np.array([1,2,3,4,5])


np.array([1,2,3,4,5],dtype=np.float32)


list_com = np.array([range(i,i+3) for i in[1,4,7]])

print(list_com) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [136]:
a = [1, 2, 3, 4, 5]
b = np.array(a)
c = np.array([1, 3, 5])

print(a)
print(b)
print(c)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
[1 3 5]


In [138]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

print(a.ndim)
print(a.shape)
print(a.dtype)

print(np.ndim(b))
print(np.shape(b))

2
(3, 3)
int32
3
(3, 2, 2)


In [208]:
np.full((2,3),5)
np.arange(0,10,2)
np.random.random((3,3))
np.random.randint(0,10,(3,3))
np.random.normal(0,1,(3,))
np.random.seed(0)
arr1 = np.random
arr1

<module 'numpy.random' from 'C:\\Users\\602-24\\anaconda3\\Lib\\site-packages\\numpy\\random\\__init__.py'>

In [216]:
a = np.array([1,2,3])

print(f"a[-1]:%d,a[-2]:%d,a[-3]:%d "%(a[-1],a[-2],a[-3]))

b = np.array([[1,5,9],[2,6,8],[3,4,7]])

print(b)

print(f"b[0,0]:%d,b[0,2]:%d,b[2,2]:%d "%(b[0,0],b[0,2],b[2,2]))


a[-1]:3,a[-2]:2,a[-3]:1 
[[1 5 9]
 [2 6 8]
 [3 4 7]]
b[0,0]:1,b[0,2]:9,b[2,2]:7 


In [218]:
a = np.array([[1, 2], [3, 4]]) 

b = np.array([[4, 3], [2, 1]]) 

print (a + b) 

print (a*b) 

print (a.dot(b)) 

[[5 5]
 [5 5]]
[[4 6]
 [6 4]]
[[ 8  5]
 [20 13]]
